import Head from 'next/head'
import Image from 'next/image';
import Banner from '../components/banner'
import styles from '../styles/Home.module.css'

export default function Home() {

  const handleOnBannerButtonClick = () => {
    console.log("Banner button clicked...");
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText={"View Stores Nearby"} handleOnClick={handleOnBannerButtonClick} />

        <Image
          alt='hero-image'
          className={styles.heroImage}
          src={"/hero-image.png"}
          width={500}
          height={400}
        />
      </main>
    </div>
  )
}
